[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base                     = "dark"
backgroundColor          = "#0c0e12"
secondaryBackgroundColor = "#11141a"
textColor                = "#cccccc"
primaryColor             = "#00ffad"
font                     = "monospace"
